### Installation du serveur VNC ###
- name: "Installation du serveur VNC"
  block:
    ### Détectionn de l'OS et de sa Version ###
    - name: Debug OS
      debug:
        msg: "Système détecté : {{ ansible_facts.distribution }} {{ ansible_facts.distribution_version }}"

    - name: "Supprimer les gestionnaires d'affichage concurrents (ex: gdm3, sddm)"
      apt:
        name: "{{ item }}"
        state: absent
      loop:
        - gdm3
        - sddm
      when: ansible_facts.distribution in ["Debian", "Ubuntu"]

    - name: Install lightdm
      apt:
        name: lightdm
        state: present

    - name: Configurer LightDM comme gestionnaire d'affichage par défaut avec debconf
      debconf:
        name: lightdm
        question: shared/default-x-display-manager
        value: /usr/sbin/lightdm
        vtype: string

    - name: Reconfigurer le gestionnaire d'affichage pour appliquer LightDM
      command: dpkg-reconfigure -f noninteractive lightdm

    - name: Reboot the system
      reboot:
        msg: "Reboot initiated by Ansible"
        pre_reboot_delay: 5
        post_reboot_delay: 10

    - name: Install x11vnc
      apt:
        name: x11vnc
        state: present

    - name: Create x11vnc service file
      copy:
        dest: /lib/systemd/system/x11vnc.service
        content: |
          [Unit]
          Description=x11vnc service
          After=display-manager.service network.target syslog.target

          [Service]
          Type=simple
          ExecStart=/usr/bin/x11vnc -forever -display :0 -auth guess -passwd {{ user_password }}
          ExecStop=/usr/bin/killall x11vnc
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable x11vnc service
      systemd:
        name: x11vnc.service
        enabled: yes
        state: started

    - name: Reboot the system
      reboot:
        msg: "Reboot initiated by Ansible"
        pre_reboot_delay: 5
        post_reboot_delay: 10

    - name: Désactiver le verrouillage automatique de l'écran
      command: gsettings set org.gnome.desktop.screensaver lock-enabled false

    - name: Désactiver les notifications sur l'écran de verrouillage
      command: gsettings set org.gnome.desktop.notifications show-in-lock-screen false

    - name: Désactiver le verrouillage de l'écran lors de la mise en veille
      command: gsettings set org.gnome.desktop.screensaver ubuntu-lock-on-suspend false
      when: ansible_facts.distribution in ["Ubuntu"]
  when: ansible_facts.distribution in ["Debian", "Ubuntu"]