---
- name: Configurer la VM avec les logiciels et services
  hosts: all
  become: true

  vars:
    software_list: []
    vscode_extensions: []
    ovpn_server_config_src: ""
    ovpn_server_config_dest: "/etc/openvpn/server.conf"
    desktop_environment: "xfce4"
    user_password: "{{ user_password }}"
    user_name: "{{ user_name }}"
    user_email: "{{ user_email }}"
    instance_id: "{{ instance_id }}"

  tasks:
    - name: Mettre à jour le système
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_facts.os_family == "Debian"

    - block:
        - name: Installer les logiciels requis
          apt:
            name: "{{ software_list }}"
            state: present
          when: software_list | length > 0

        - name: Installer Visual Studio Code
          shell: |
            curl -fsSL https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64 -o vscode.deb
            apt install ./vscode.deb -y
          args:
            creates: /usr/bin/code

        - name: Installer les extensions VSCode
          shell: code --install-extension {{ item }}
          loop: "{{ vscode_extensions }}"
          when: vscode_extensions | length > 0

      when: ansible_facts.os_family == "Debian"

    - name: Installer OpenVPN et Easy-RSA
      apt:
        name:
          - openvpn
          - easy-rsa
        state: present

    - name: Configurer l'environnement de bureau et RDP
      block:
        - name: Installer les packages graphiques
          apt:
            name:
              - "{{ desktop_environment }}"
              - xrdp
              - tightvncserver
            state: present

        - name: Configurer xrdp
          copy:
            content: |
              [Session]
              Command=startxfce4
            dest: "/etc/xrdp/startwm.sh"
            mode: 0755

        - name: Activer et démarrer xrdp
          systemd:
            name: xrdp
            enabled: yes
            state: started

      when: ansible_facts.os_family == "Debian"

    - name: Configurer OpenVPN
      block:
        - name: Copier le fichier de configuration OpenVPN
          template:
            src: "{{ ovpn_server_config_src }}"
            dest: "{{ ovpn_server_config_dest }}"
            mode: 0644

        - name: Générer les certificats
          shell: |
            cd /etc/openvpn/easy-rsa
            ./easyrsa build-server-full server nopass
            ./easyrsa gen-crl
          args:
            creates: "/etc/openvpn/easy-rsa/pki/issued/server.crt"

        - name: Activer OpenVPN
          service:
            name: openvpn@server
            state: started
            enabled: yes

      when: ansible_facts.os_family == "Debian"

    - name: Activer et configurer RDP sous Windows
      block:
        - name: Activer le service RDP
          win_service:
            name: "TermService"
            start_mode: auto
            state: started

        - name: Ajouter l'utilisateur au groupe Administrateurs
          win_user:
            name: "{{ user_name }}"
            password: "{{ user_password }}"
            update_password: on_create
            state: present
            groups:
              - "Administrators"

        - name: Ouvrir le port RDP dans le pare-feu
          win_firewall_rule:
            name: "Allow RDP"
            enable: yes
            localport: 3389
            protocol: TCP
            direction: in
            action: allow

        - name: Configurer la clé de registre pour RDP
          win_regedit:
            path: "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server"
            name: "fDenyTSConnections"
            data: 0
            type: dword

        - name: Redémarrer le service RDP
          win_service:
            name: "TermService"
            state: restarted

      when: ansible_facts.system == "Windows"
