---
- name: Configurer la VM avec les logiciels et services sous Linux
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - common.yml
 
  tasks:
    - name: Debug OS
      debug:
        msg: "Système détecté : {{ ansible_facts.distribution }} {{ ansible_facts.distribution_version }}"
 
    ### Mise à jour du système ###
    - name: Mettre à jour le système
      package:
        name: "*"
        state: latest
      when: ansible_facts.distribution in ["Debian", "Ubuntu"]
 
    ### Vérifier et installer Git ###
    - name: Vérifier si Git est installé
      command: git --version
      register: git_installed
      failed_when: false
      changed_when: false
 
    - name: Installer Git si non présent
      apt:
        name: git
        state: present
      when: git_installed.rc != 0
 
    ### Installer la dépendance libasound2 avant VSCode ###
    - name: Installer la dépendance libasound2t64
      apt:
        name: libasound2t64
        state: present
        update_cache: yes
      when: ansible_facts.distribution in ["Debian", "Ubuntu"]
 
    ### Télécharger et installer Visual Studio Code ###
    - name: Télécharger VSCode
      get_url:
        url: https://go.microsoft.com/fwlink/?LinkID=760868
        dest: /tmp/vscode.deb
      when: ansible_facts.distribution in ["Debian", "Ubuntu"]
 
    - name: Installer VSCode via le fichier deb
      apt:
        deb: /tmp/vscode.deb
      when: ansible_facts.distribution in ["Debian", "Ubuntu"]
 
    ### Logiciels supplémentaires ###
    - name: Installer les logiciels listés dans software_list
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ software_list | default([]) }}"
      when: software_list | default([]) | length > 0
 
    ### XFCE + VNC ###
    - name: Installer VNC et XFCE
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - tightvncserver
        - xfce4
      when: ansible_facts.distribution in ["Debian", "Ubuntu"]
 
    - name: Créer le répertoire .vnc
      file:
        path: /home/ubuntu/.vnc
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
 
    - name: Configurer le fichier xstartup
      copy:
        content: |
          #!/bin/sh
          startxfce4
        dest: /home/ubuntu/.vnc/xstartup
        mode: '0755'
 
    - name: Démarrer VNC Server au démarrage
      systemd:
        daemon_reload: yes
        name: vncserver@1.service
        enabled: yes
        state: started
 
    ### Configuration RDP ###
    - block:
        - name: Installer les packages XFCE + xrdp
          apt:
            name:
              - "{{ desktop_environment }}"
              - xrdp
            state: present
 
        - name: Configurer xrdp
          copy:
            content: |
              #!/bin/sh
              startxfce4
            dest: /etc/xrdp/startwm.sh
            mode: 0755
 
        - name: Activer et démarrer xrdp
          systemd:
            name: xrdp
            enabled: yes
            state: started
 
    ### Installation et configuration de VNC Server ###
    - block:
        - name: Configurer VNC pour démarrer avec XFCE
          copy:
            dest: /etc/systemd/system/vncserver@.service
            content: |
              [Unit]
              Description=Start TightVNC server at startup
              After=syslog.target network.target
 
              [Service]
              Type=forking
              User={{ user_name }}
              PAMName=login
              PIDFile=/home/{{ user_name }}/.vnc/%H:%i.pid
              ExecStartPre=-/usr/bin/vncserver -kill :%i > /dev/null 2>&1
              ExecStart=/usr/bin/vncserver :%i -geometry 1920x1080 -depth 24
              ExecStop=/usr/bin/vncserver -kill :%i
 
              [Install]
              WantedBy=multi-user.target
 
        - name: Démarrer VNC Server au démarrage
          systemd:
            daemon_reload: yes
            name: vncserver@1.service
            enabled: yes
            state: started
 
        - name: Créer un mot de passe pour VNC
          ansible.builtin.shell: |
            echo '{{ user_password }}' | vncpasswd -f > /home/{{ user_name }}/.vnc/passwd
          args:
            creates: /home/{{ user_name }}/.vnc/passwd
          become: true
          become_user: "{{ user_name }}"
          no_log: true
 
        - name: Ajuster les permissions du fichier VNC
          file:
            path: /home/{{ user_name }}/.vnc/passwd
            owner: "{{ user_name }}"
            group: "{{ user_name }}"
            mode: '0600'
      when: ansible_facts.os_family == "Debian"
 
